[project]
name = "ai-cv-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "playwright>=1.54.0",
    "pyyaml>=6.0.2",
    "pydantic>=2.0.0",
    "trafilatura>=2.0.0",
]
