name: Ruff CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  ruff:
    name: Ruff Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Lint (diagnostics only)
      - name: Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: check

      # Enforce formatting (fails if formatting changes needed)
      - name: Ruff Format Check
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check

      # Optional: show version (helps debugging)
      - name: Show Ruff Version
        run: ruff --version
